produtos = [
    {
        'id': 1,
        'marca': 'Apple',
        'nome': 'iPhone 13',
        'ano': '2021',
        'categoria': 1,
    },
    {
        'id': 2,
        'marca': 'Samsung',
        'nome': 'Galaxy S21',
        'ano': '2021',
        'categoria': 1,
    },
    {
        'id': 3,
        'marca': 'Sony',
        'nome': 'PlayStation 5',
        'ano': '2020',
        'categoria': 2,
    },
    {
        'id': 4,
        'marca': 'Dell',
        'nome': 'XPS 13',
        'ano': '2021',
        'categoria': 3,
    },
    {
        'id': 5,
        'marca': 'Microsoft',
        'nome': 'Surface Pro 7',
        'ano': '2019',
        'categoria': 4,
    },
    {
        'id': 6,
        'marca': 'Apple',
        'nome': 'MacBook Air',
        'ano': '2020',
        'categoria': 3,
    },
    {
        'id': 7,
        'marca': 'HP',
        'nome': 'Envy 13',
        'ano': '2021',
        'categoria': 3,
    },
    {
        'id': 8,
        'marca': 'Canon',
        'nome': 'EOS R5',
        'ano': '2020',
        'categoria': 5,
    },
    {
        'id': 9,
        'marca': 'Nikon',
        'nome': 'Z7 II',
        'ano': '2020',
        'categoria': 5,
    },
    {
        'id': 10,
        'marca': 'LG',
        'nome': 'OLED CX',
        'ano': '2020',
        'categoria': 6,
    },
    {
        'id': 11,
        'marca': 'Sony',
        'nome': 'Bravia X90J',
        'ano': '2021',
        'categoria': 6,
    },
    {
        'id': 12,
        'marca': 'Bose',
        'nome': 'QuietComfort 35 II',
        'ano': '2017',
        'categoria': 7,
    },
    {
        'id': 13,
        'marca': 'Apple',
        'nome': 'AirPods Pro',
        'ano': '2019',
        'categoria': 7,
    },
    {
        'id': 14,
        'marca': 'Fitbit',
        'nome': 'Charge 4',
        'ano': '2020',
        'categoria': 8,
    },
    {
        'id': 15,
        'marca': 'Garmin',
        'nome': 'Forerunner 945',
        'ano': '2019',
        'categoria': 8,
    },
    {
        'id': 16,
        'marca': 'GoPro',
        'nome': 'Hero 9',
        'ano': '2020',
        'categoria': 5,
    },
    {
        'id': 17,
        'marca': 'Sony',
        'nome': 'WH-1000XM4',
        'ano': '2020',
        'categoria': 7,
    },
    {
        'id': 18,
        'marca': 'Apple',
        'nome': 'iPad Pro',
        'ano': '2021',
        'categoria': 4,
    },
    {
        'id': 19,
        'marca': 'Asus',
        'nome': 'ROG Strix G15',
        'ano': '2021',
        'categoria': 3,
    },
    {
        'id': 20,
        'marca': 'Microsoft',
        'nome': 'Xbox Series X',
        'ano': '2020',
        'categoria': 2,
    },
]
